enyo.depends(
	"MainCtrl.js",
	"AutoUploadCtrl.js",
	"ImageSpiderCtrl.js",
	"ImageUploadCtrl.js",
	"IndexCtrl.js",
	"HeaderCtrl.js",
	"NavCtrl.js",
	"ClientConfigCtrl.js",
	"ServerConfigCtrl.js"
);